### ISSUE TITLE
Doesn't work with panorama/photosphere captured from Google Camera

### ISSUE THREAD

**Issue by kevintanhongann** [ejeinc/RajawaliCardboardExample#2]
![panotest](https://cloud.githubusercontent.com/assets/359537/8760296/df24dde2-2d45-11e5-8e38-5ae6032b9300.jpg)

Was playing around with this sample app. Not sure if the image is too big or what, trying to output a better stacktrace to see what's going on. Do test.

**Comment by niusounds** [comment]
It seems too big image size. Some devices cannot load images over than about 4096x4096.

And also, your image is not an equirectangular panorama image.
RajawaliCardboardExample uses Sphere to map texture. So it supports only equirectangular panorama.

**Comment by kevintanhongann** [comment]
@niusounds okay cool. Thanks for the pointers. I'll look into it further. 

But one question regarding Photospheres taken with a Google Camera. What type of panorama is that, and how can I render that so that it shapes nicely in a spherical view as rendered using the Photosphere intent in Google Play Services API?

**Comment by punkete1990** [comment]
Hi @niusounds, I need to load a big image (~15MB), any idea?

**Comment by kevintanhongann** [comment]
@punkete1990 as @niusounds said, you need to downscale the image to a compatible size to view.
